/** Banks, neobanks and brokers for Patrimonio (Spain + widely used internationally). */

export const SPANISH_BANK_IDS = [
  // Bancos tradicionales (España)
  'caixabank',
  'bbva',
  'santander',
  'sabadell',
  'bankinter',
  'unicaja',
  'abanca',
  'kutxabank',
  'ibercaja',
  'cajamar',
  'arquia',
  'deutscheBank',
  'citibank',
  'bnpparibas',
  'hsbc',
  'barclays',
  // Neobancos y cuentas digitales
  'ing',
  'openbank',
  'evo',
  'imagin',
  'mediolanum',
  'wizink',
  'bnext',
  'n26',
  'revolut',
  'wise',
  'bunq',
  'vivid',
  // Roboadvisors, brókers y plataformas de inversión
  'indexa',
  'myinvestor',
  'tradeRepublic',
  'degiro',
  'interactiveBrokers',
  'etoro',
  'xtb',
  'renta4',
  'selfBank',
  'scalable',
  'inbestme',
  'finizens',
  'andbank',
  'freedom24',
  'lightyear',
  'flatex',
  'clicktrade',
  'coinbase',
  'paypal',
  'other',
];

/** Maps legacy free-text values to institution ids. */
export const SPANISH_BANK_LEGACY_LABELS = {
  CaixaBank: 'caixabank',
  'La Caixa': 'caixabank',
  BBVA: 'bbva',
  Santander: 'santander',
  'Banco Santander': 'santander',
  Sabadell: 'sabadell',
  'Banco Sabadell': 'sabadell',
  Bankinter: 'bankinter',
  Unicaja: 'unicaja',
  'Unicaja Banco': 'unicaja',
  Abanca: 'abanca',
  Kutxabank: 'kutxabank',
  Ibercaja: 'ibercaja',
  Cajamar: 'cajamar',
  Arquia: 'arquia',
  'Deutsche Bank': 'deutscheBank',
  Citibank: 'citibank',
  'BNP Paribas': 'bnpparibas',
  HSBC: 'hsbc',
  Barclays: 'barclays',
  ING: 'ing',
  'ING Direct': 'ing',
  Openbank: 'openbank',
  'Evo Banco': 'evo',
  Imagin: 'imagin',
  Mediolanum: 'mediolanum',
  'Banco Mediolanum': 'mediolanum',
  WiZink: 'wizink',
  Wizink: 'wizink',
  Bnext: 'bnext',
  N26: 'n26',
  Revolut: 'revolut',
  Wise: 'wise',
  TransferWise: 'wise',
  Bunq: 'bunq',
  Vivid: 'vivid',
  'Indexa Capital': 'indexa',
  Indexa: 'indexa',
  Myinvestor: 'myinvestor',
  'Trade Republic': 'tradeRepublic',
  Degiro: 'degiro',
  'Interactive Brokers': 'interactiveBrokers',
  IBKR: 'interactiveBrokers',
  eToro: 'etoro',
  Etoro: 'etoro',
  XTB: 'xtb',
  'Renta 4': 'renta4',
  Renta4: 'renta4',
  'Self Bank': 'selfBank',
  Selfbank: 'selfBank',
  'Scalable Capital': 'scalable',
  Scalable: 'scalable',
  Inbestme: 'inbestme',
  Finizens: 'finizens',
  Andbank: 'andbank',
  Freedom24: 'freedom24',
  Lightyear: 'lightyear',
  Flatex: 'flatex',
  Clicktrade: 'clicktrade',
  Coinbase: 'coinbase',
  PayPal: 'paypal',
  Otro: 'other',
  Other: 'other',
};
